# Generated by Django 3.2.10 on 2021-12-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description_short', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('description_Long', models.TextField(verbose_name='Полное описание')),
                ('coordinates_lng', models.CharField(max_length=17, verbose_name='Координаты долгота')),
                ('coordinates_lat', models.CharField(max_length=17, verbose_name='Координаты широта')),
            ],
        ),
    ]
