# Generated by Django 3.2.10 on 2021-12-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('image_order', models.IntegerField(verbose_name='Порядок сортировки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='Куда пойти')),
            ],
        ),
    ]
