# Generated by Django 3.2.10 on 2021-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_description_long_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(default=0, verbose_name='СОртировка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Координаты широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Координаты долгота'),
        ),
    ]
