# Generated by Django 3.2.10 on 2021-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
    ]
