# Generated by Django 3.2.10 on 2021-12-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.place', verbose_name='Куда пойти'),
        ),
    ]
